### ISSUE TITLE
Use npm version directly?

### ISSUE THREAD

**Issue by bclinkinbeard** [boennemann/semantic-release#14] opened 2015-03-10 15:50 UTC
As mentioned in #11, this would add support for shrinkwrap.json, and it should also allow the version number to be kept in package.json, which I personally think would be a big improvement. Would love to know your thoughts.

https://docs.npmjs.com/cli/version

**Comment by boennemann** [comment] 2015-03-10 23:08
Hey @bclinkinbeard,

while using `npm version` brings shrinkwrap.json support it wouldn't bring back the version in package.json.
The thing is that releases happen on the CI, and as long the CI doesn't push back to your repo (which is a bad idea) the changes/commits/tags are just cleaned away.

I'm closing this as it's a duplicate of #11 now, but I'm happy to further discuss :)

Best,
Stephan

**Closed by boennemann** 2015-03-10 23:08 UTC
