### ISSUE TITLE
semantic-release always wants to publish v1.0.0

### ISSUE THREAD

**Issue by arlac77** [boennemann/semantic-release#46] opened 2015-06-21 12:08 UTC
after successful publishing of v1.0.0 semantic-release stays at v1.0.0 even after two commits (refactor + feat).

a1feefe5f1a1a4b7ee25bc34bed4c9984fce0c48 -> v1.0.0 ok
73032331d9fcece165e10a1816fe3de93ab9cd0e -> v1.0.0 why?
61fa7cf86528e04f4c556b4f06e472770dbc1123 -> v1.0.0 why?

---- arlac77/uti changelog ---
commit 74a84ce4ec9351e00d40b1f0d2daef8bdd12e887
Author: Markus Felten <Markus.Felten@gmx.de>
Date:   Sun Jun 21 13:45:16 2015 +0200

    version=1.0.0 (maybe that helps semantic-release a bit)

commit 61fa7cf86528e04f4c556b4f06e472770dbc1123
Author: Markus Felten <Markus.Felten@gmx.de>
Date:   Sun Jun 21 13:41:04 2015 +0200

    refactor(initialize): removed one unnecessary Promise layer

commit 73032331d9fcece165e10a1816fe3de93ab9cd0e
Author: Markus Felten <Markus.Felten@gmx.de>
Date:   Sun Jun 21 13:37:22 2015 +0200

    feat: org.gnu.gnu-zip-tar-archive and public.zip-archive added to the predefined public UTIs

commit a1feefe5f1a1a4b7ee25bc34bed4c9984fce0c48
Author: Markus Felten <Markus.Felten@gmx.de>
Date:   Sat Jun 20 16:44:38 2015 +0200

    trying to fix travis deploy -> nvm
----

**Comment by boennemann** [comment] 2015-06-21 23:36
Thanks for the report, I'm investigating this now.

**Comment by boennemann** [comment] 2015-06-21 23:55
Okay given that the npm credentials were correctly setup for releasing 1.0.0 this indeed seems to be a regression (also the same and real reason for #45).

1.1.0 should have been released for 73032331d9fcece165e10a1816fe3de93ab9cd0e, and as you only pushed on 61fa7cf86528e04f4c556b4f06e472770dbc1123 it should've happened there.

74a84ce4ec9351e00d40b1f0d2daef8bdd12e887 breaks it for real though, so please revert that.

The only recent change that messed with this logic is this 3.4.0 https://github.com/boennemann/semantic-release/releases/tag/v3.4.0 (cc @christophwitzko).
Can you please pin the semantic-release dependency to 3.3.2 https://github.com/boennemann/semantic-release/releases/tag/v3.3.2 and tell me if it works then?

Thanks for your patience,

Stephan

**Comment by arlac77** [comment] 2015-06-22 06:44
going back to:
version: 0.0.0-semantically-released
semantic-release: 3.3.2

produced v1.1.0

**Comment by boennemann** [comment] 2015-06-25 17:18
@christophwitzko Do you think is related to the private module support? Can we add `npm-registry-client` as a quick fix here?

**Comment by boennemann** [comment] 2015-06-25 23:40
Alright In the meantime I've moved the latest tag on npm back to version 3.3.2 so the problematic version will no longer be installed by default. We're still looking for a fix here.

**Comment by boennemann** [comment] 2015-07-16 11:50
We won't fix this in the 3.x range. 4.x is due very soon.

**Closed by boennemann** 2015-07-16 11:50 UTC
Labels: fix
